name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Create Capacitor project
      run: |
        npm init -y
        npm install @capacitor/core @capacitor/cli @capacitor/android
        mkdir www
        cp *.html www/ 2>/dev/null || true
        cp *.json www/ 2>/dev/null || true
        cp *.js www/ 2>/dev/null || true
        cp *.png www/ 2>/dev/null || true
        npx cap init "Cable Calculator" "com.example.cablecalc" --web-dir=www
        npx cap add android
        npx cap sync
        
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: cable-calculator-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
